name = "avatar-email-worker"
main = "email-worker.js"
compatibility_date = "2024-10-22"
workers_dev = true

[vars]
# INTAKE_ENDPOINT = "https://your-domain.com/api/intake/email"
# INTAKE_SECRET = "<set the same secret as in your Next.js server>"
# DOMAIN_BUSINESS_MAP = "{\"paqva.com\":\"PAQVA\"}"
