name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/supabase-functions-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy all Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase functions deploy on-ticket-status --project-ref "$PROJECT_REF" --non-interactive
          supabase functions deploy email-to-ticket --project-ref "$PROJECT_REF" --non-interactive || true
          supabase functions deploy inbound-email --project-ref "$PROJECT_REF" --non-interactive || true
          supabase functions deploy on-comment-created --project-ref "$PROJECT_REF" --non-interactive || true
